//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public int Account_No { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int MobNo { get; set; }
        public System.DateTime DOB { get; set; }
        public double Balance { get; set; }
        public string Password { get; set; }
        public string AccountType { get; set; }
    }
}
